"""initial schema

Revision ID: 17f69ea12754
Revises:
Create Date: 2026-08-18 16:48:20.161791
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "17f69ea12754"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("parent_department_id", sa.Uuid(), nullable=True),
        sa.Column("department_name", sa.String(), nullable=False),
        sa.Column("department_type", sa.String(), nullable=False),
        sa.Column("department_path", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_department_id"],
            ["departments.department_id"],
            name=op.f("fk_departments_parent_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("department_id", name=op.f("pk_departments")),
    )
    op.create_index(
        op.f("ix_departments_parent_department_id"),
        "departments",
        ["parent_department_id"],
        unique=False,
    )
    op.create_index(op.f("ix_departments_status"), "departments", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("employee_no", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("manager_employee_no", sa.String(), nullable=True),
        sa.Column("org_level", sa.String(), nullable=True),
        sa.Column("wecom_user_id", sa.String(), nullable=True),
        sa.Column("role_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.department_id"],
            name=op.f("fk_users_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["manager_employee_no"],
            ["users.employee_no"],
            name=op.f("fk_users_manager_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("employee_no", name=op.f("pk_users")),
        sa.UniqueConstraint("wecom_user_id", name=op.f("uq_users_wecom_user_id")),
    )
    op.create_index(op.f("ix_users_department_id"), "users", ["department_id"], unique=False)
    op.create_index(
        op.f("ix_users_manager_employee_no"), "users", ["manager_employee_no"], unique=False
    )
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_table(
        "task_inputs",
        sa.Column("input_id", sa.Uuid(), nullable=False),
        sa.Column("input_type", sa.String(), nullable=False),
        sa.Column("raw_text", sa.String(), nullable=True),
        sa.Column("voice_file_url", sa.String(), nullable=True),
        sa.Column("asr_text", sa.String(), nullable=True),
        sa.Column("source_channel", sa.String(), nullable=False),
        sa.Column("submitted_by_employee_no", sa.String(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["submitted_by_employee_no"],
            ["users.employee_no"],
            name=op.f("fk_task_inputs_submitted_by_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("input_id", name=op.f("pk_task_inputs")),
    )
    op.create_index(
        op.f("ix_task_inputs_submitted_at"), "task_inputs", ["submitted_at"], unique=False
    )
    op.create_index(
        op.f("ix_task_inputs_submitted_by_employee_no"),
        "task_inputs",
        ["submitted_by_employee_no"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("task_no", sa.String(), nullable=True),
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column("task_description", sa.String(), nullable=True),
        sa.Column("task_goal", sa.String(), nullable=True),
        sa.Column("task_source", sa.String(), nullable=True),
        sa.Column("creator_employee_no", sa.String(), nullable=False),
        sa.Column("main_assignee_employee_no", sa.String(), nullable=True),
        sa.Column("report_to_employee_no", sa.String(), nullable=True),
        sa.Column("report_to_level", sa.String(), nullable=True),
        sa.Column("reviewer_employee_no", sa.String(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_hours", sa.Numeric(), nullable=True),
        sa.Column("actual_hours", sa.Numeric(), nullable=True),
        sa.Column("task_weight", sa.Integer(), nullable=True),
        sa.Column("deliverable", sa.String(), nullable=True),
        sa.Column("acceptance_criteria", sa.String(), nullable=True),
        sa.Column("is_urgent", sa.Boolean(), nullable=True),
        sa.Column("report_cycle", sa.String(), nullable=True),
        sa.Column("cancel_reason", sa.String(), nullable=True),
        sa.Column("withdraw_reason", sa.String(), nullable=True),
        sa.Column("close_reason", sa.String(), nullable=True),
        sa.Column("merged_into_task_id", sa.Uuid(), nullable=True),
        sa.Column("task_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "actual_hours IS NULL OR actual_hours >= 0",
            name=op.f("ck_tasks_actual_hours_non_negative"),
        ),
        sa.CheckConstraint(
            "estimated_hours IS NULL OR estimated_hours >= 0",
            name=op.f("ck_tasks_estimated_hours_non_negative"),
        ),
        sa.CheckConstraint(
            "merged_into_task_id IS NULL OR merged_into_task_id <> task_id",
            name=op.f("ck_tasks_not_merged_into_self"),
        ),
        sa.CheckConstraint("task_version >= 1", name=op.f("ck_tasks_task_version_positive")),
        sa.CheckConstraint(
            "task_weight IS NULL OR task_weight BETWEEN 1 AND 5",
            name=op.f("ck_tasks_task_weight_range"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_employee_no"],
            ["users.employee_no"],
            name=op.f("fk_tasks_creator_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.department_id"],
            name=op.f("fk_tasks_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["main_assignee_employee_no"],
            ["users.employee_no"],
            name=op.f("fk_tasks_main_assignee_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_task_id"],
            ["tasks.task_id"],
            name=op.f("fk_tasks_merged_into_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_to_employee_no"],
            ["users.employee_no"],
            name=op.f("fk_tasks_report_to_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_employee_no"],
            ["users.employee_no"],
            name=op.f("fk_tasks_reviewer_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("task_no", name=op.f("uq_tasks_task_no")),
    )
    op.create_index(op.f("ix_tasks_created_at"), "tasks", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_tasks_creator_employee_no"), "tasks", ["creator_employee_no"], unique=False
    )
    op.create_index(op.f("ix_tasks_deadline"), "tasks", ["deadline"], unique=False)
    op.create_index(op.f("ix_tasks_department_id"), "tasks", ["department_id"], unique=False)
    op.create_index(
        op.f("ix_tasks_main_assignee_employee_no"),
        "tasks",
        ["main_assignee_employee_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_merged_into_task_id"), "tasks", ["merged_into_task_id"], unique=False
    )
    op.create_index(
        op.f("ix_tasks_report_to_employee_no"), "tasks", ["report_to_employee_no"], unique=False
    )
    op.create_index(
        op.f("ix_tasks_reviewer_employee_no"), "tasks", ["reviewer_employee_no"], unique=False
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "ai_extraction_records",
        sa.Column("extraction_id", sa.Uuid(), nullable=False),
        sa.Column("input_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("extracted_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("low_confidence_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirm_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence_score", sa.Numeric(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["input_id"],
            ["task_inputs.input_id"],
            name=op.f("fk_ai_extraction_records_input_id_task_inputs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_ai_extraction_records_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("extraction_id", name=op.f("pk_ai_extraction_records")),
    )
    op.create_index(
        op.f("ix_ai_extraction_records_input_id"),
        "ai_extraction_records",
        ["input_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_extraction_records_task_id"), "ai_extraction_records", ["task_id"], unique=False
    )
    op.create_table(
        "task_nodes",
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("node_order", sa.Integer(), nullable=False),
        sa.Column("sort_weight", sa.Integer(), nullable=False),
        sa.Column("node_name", sa.String(), nullable=False),
        sa.Column("action_detail", sa.String(), nullable=True),
        sa.Column("tools_or_materials", sa.String(), nullable=True),
        sa.Column("owner_employee_no", sa.String(), nullable=True),
        sa.Column("planned_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_hours", sa.Numeric(), nullable=True),
        sa.Column("actual_hours", sa.Numeric(), nullable=True),
        sa.Column("deliverable", sa.String(), nullable=True),
        sa.Column("acceptance_criteria", sa.String(), nullable=True),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "actual_hours IS NULL OR actual_hours >= 0",
            name=op.f("ck_task_nodes_actual_hours_non_negative"),
        ),
        sa.CheckConstraint(
            "estimated_hours IS NULL OR estimated_hours >= 0",
            name=op.f("ck_task_nodes_estimated_hours_non_negative"),
        ),
        sa.CheckConstraint("node_order >= 1", name=op.f("ck_task_nodes_node_order_positive")),
        sa.CheckConstraint(
            "planned_start_time IS NULL OR planned_deadline IS NULL "
            "OR planned_deadline >= planned_start_time",
            name=op.f("ck_task_nodes_planned_time_order"),
        ),
        sa.CheckConstraint(
            "progress_percent >= 0 AND progress_percent <= 100",
            name=op.f("ck_task_nodes_progress_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_employee_no"],
            ["users.employee_no"],
            name=op.f("fk_task_nodes_owner_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_task_nodes_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("node_id", name=op.f("pk_task_nodes")),
        sa.UniqueConstraint("task_id", "node_id", name="uq_task_nodes_task_node"),
    )
    op.create_index(
        op.f("ix_task_nodes_owner_employee_no"), "task_nodes", ["owner_employee_no"], unique=False
    )
    op.create_index(
        op.f("ix_task_nodes_planned_deadline"), "task_nodes", ["planned_deadline"], unique=False
    )
    op.create_index(op.f("ix_task_nodes_status"), "task_nodes", ["status"], unique=False)
    op.create_index(
        "ix_task_nodes_task_order",
        "task_nodes",
        ["task_id", "node_order", "sort_weight"],
        unique=False,
    )
    op.create_table(
        "task_participants",
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("employee_no", sa.String(), nullable=False),
        sa.Column("participant_role", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("confirm_status", sa.String(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT is_primary OR participant_role = 'assignee'",
            name=op.f("ck_task_participants_primary_is_assignee"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_no"],
            ["users.employee_no"],
            name=op.f("fk_task_participants_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_task_participants_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("participant_id", name=op.f("pk_task_participants")),
        sa.UniqueConstraint(
            "task_id",
            "employee_no",
            "participant_role",
            name="uq_task_participants_task_employee_role",
        ),
    )
    op.create_index(
        op.f("ix_task_participants_employee_no"), "task_participants", ["employee_no"], unique=False
    )
    op.create_index(
        "uq_task_participants_one_primary_assignee",
        "task_participants",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("participant_role = 'assignee' AND is_primary IS TRUE"),
    )
    op.create_table(
        "task_status_logs",
        sa.Column("status_log_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(), nullable=True),
        sa.Column("to_status", sa.String(), nullable=False),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("operator_employee_no", sa.String(), nullable=True),
        sa.Column("target_employee_no", sa.String(), nullable=True),
        sa.Column("task_version", sa.Integer(), nullable=False),
        sa.Column("business_ref_type", sa.String(), nullable=True),
        sa.Column("business_ref_id", sa.Uuid(), nullable=True),
        sa.Column("operation_source", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(business_ref_type IS NULL AND business_ref_id IS NULL) "
            "OR (business_ref_type IS NOT NULL AND business_ref_id IS NOT NULL)",
            name=op.f("ck_task_status_logs_business_ref_pair"),
        ),
        sa.CheckConstraint(
            "task_version >= 1", name=op.f("ck_task_status_logs_task_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["operator_employee_no"],
            ["users.employee_no"],
            name=op.f("fk_task_status_logs_operator_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_employee_no"],
            ["users.employee_no"],
            name=op.f("fk_task_status_logs_target_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_task_status_logs_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("status_log_id", name=op.f("pk_task_status_logs")),
    )
    op.create_index(
        op.f("ix_task_status_logs_action_type"), "task_status_logs", ["action_type"], unique=False
    )
    op.create_index(
        "ix_task_status_logs_business_ref",
        "task_status_logs",
        ["business_ref_type", "business_ref_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_status_logs_operator_employee_no"),
        "task_status_logs",
        ["operator_employee_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_status_logs_target_employee_no"),
        "task_status_logs",
        ["target_employee_no"],
        unique=False,
    )
    op.create_index(
        "ix_task_status_logs_task_timeline",
        "task_status_logs",
        ["task_id", "created_at", "status_log_id"],
        unique=False,
    )
    op.create_table(
        "task_node_dependencies",
        sa.Column("dependency_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("predecessor_node_id", sa.Uuid(), nullable=False),
        sa.Column("successor_node_id", sa.Uuid(), nullable=False),
        sa.Column("dependency_type", sa.String(), nullable=False),
        sa.CheckConstraint(
            "predecessor_node_id <> successor_node_id",
            name=op.f("ck_task_node_dependencies_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "predecessor_node_id"],
            ["task_nodes.task_id", "task_nodes.node_id"],
            name="fk_task_node_dependencies_predecessor_same_task",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "successor_node_id"],
            ["task_nodes.task_id", "task_nodes.node_id"],
            name="fk_task_node_dependencies_successor_same_task",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_task_node_dependencies_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("dependency_id", name=op.f("pk_task_node_dependencies")),
        sa.UniqueConstraint(
            "predecessor_node_id",
            "successor_node_id",
            "dependency_type",
            name="uq_task_node_dependencies_edge_type",
        ),
    )
    op.create_index(
        op.f("ix_task_node_dependencies_successor_node_id"),
        "task_node_dependencies",
        ["successor_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_node_dependencies_task_id"),
        "task_node_dependencies",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "task_node_participants",
        sa.Column("node_participant_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("employee_no", sa.String(), nullable=False),
        sa.Column("participant_role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_no"],
            ["users.employee_no"],
            name=op.f("fk_task_node_participants_employee_no_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "node_id"],
            ["task_nodes.task_id", "task_nodes.node_id"],
            name="fk_task_node_participants_node_same_task",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_task_node_participants_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("node_participant_id", name=op.f("pk_task_node_participants")),
        sa.UniqueConstraint(
            "task_id",
            "node_id",
            "employee_no",
            "participant_role",
            name="uq_task_node_participants_task_node_employee_role",
        ),
    )
    op.create_index(
        op.f("ix_task_node_participants_employee_no"),
        "task_node_participants",
        ["employee_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_node_participants_node_id"),
        "task_node_participants",
        ["node_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_node_participants_node_id"), table_name="task_node_participants")
    op.drop_index(
        op.f("ix_task_node_participants_employee_no"), table_name="task_node_participants"
    )
    op.drop_table("task_node_participants")
    op.drop_index(op.f("ix_task_node_dependencies_task_id"), table_name="task_node_dependencies")
    op.drop_index(
        op.f("ix_task_node_dependencies_successor_node_id"), table_name="task_node_dependencies"
    )
    op.drop_table("task_node_dependencies")
    op.drop_index("ix_task_status_logs_task_timeline", table_name="task_status_logs")
    op.drop_index(op.f("ix_task_status_logs_target_employee_no"), table_name="task_status_logs")
    op.drop_index(op.f("ix_task_status_logs_operator_employee_no"), table_name="task_status_logs")
    op.drop_index("ix_task_status_logs_business_ref", table_name="task_status_logs")
    op.drop_index(op.f("ix_task_status_logs_action_type"), table_name="task_status_logs")
    op.drop_table("task_status_logs")
    op.drop_index(
        "uq_task_participants_one_primary_assignee",
        table_name="task_participants",
        postgresql_where=sa.text("participant_role = 'assignee' AND is_primary IS TRUE"),
    )
    op.drop_index(op.f("ix_task_participants_employee_no"), table_name="task_participants")
    op.drop_table("task_participants")
    op.drop_index("ix_task_nodes_task_order", table_name="task_nodes")
    op.drop_index(op.f("ix_task_nodes_status"), table_name="task_nodes")
    op.drop_index(op.f("ix_task_nodes_planned_deadline"), table_name="task_nodes")
    op.drop_index(op.f("ix_task_nodes_owner_employee_no"), table_name="task_nodes")
    op.drop_table("task_nodes")
    op.drop_index(op.f("ix_ai_extraction_records_task_id"), table_name="ai_extraction_records")
    op.drop_index(op.f("ix_ai_extraction_records_input_id"), table_name="ai_extraction_records")
    op.drop_table("ai_extraction_records")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_reviewer_employee_no"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_report_to_employee_no"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_merged_into_task_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_main_assignee_employee_no"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_department_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_deadline"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_creator_employee_no"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_created_at"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_task_inputs_submitted_by_employee_no"), table_name="task_inputs")
    op.drop_index(op.f("ix_task_inputs_submitted_at"), table_name="task_inputs")
    op.drop_table("task_inputs")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_manager_employee_no"), table_name="users")
    op.drop_index(op.f("ix_users_department_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_departments_status"), table_name="departments")
    op.drop_index(op.f("ix_departments_parent_department_id"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
